name: Finance Daily YouTube Bot

on:
  schedule:
    - cron: "30 14 * * *" # 8:00 PM IST = 14:30 UTC every day
  workflow_dispatch: # allows manual trigger from GitHub UI anytime

jobs:
  post-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependency ffmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Install Python libraries
        run: |
          pip install groq
          pip install moviepy==1.0.3
          pip install Pillow
          pip install gtts
          pip install requests
          pip install feedparser
          pip install google-api-python-client
          pip install google-auth-httplib2
          pip install google-auth-oauthlib

      - name: Write YouTube token from secret
        run: echo '${{ secrets.YOUTUBE_TOKEN }}' > token.json

      - name: Run pipeline
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python main.py
